#!/bin/bash

linenum=`grep -n detlist *_wfs.xml | head -n 1 | awk '{print $1}' | sed "s/://"`
for i in {1..5}; do
	coefline=$((linenum+$1))
	sed "${coefline}!d" *.s00$i.opt.xml | awk '{print $3}'
done
