#!/bin/bash

for i in {1..5}; do
	linenum=`grep -n detlist *.s00$i.opt.xml | head -n 1 | awk '{print $1}' | sed "s/://"`
	coefline=$((linenum+$1))
	det=`sed "${coefline}!d" *.s00$i.opt.xml | awk '{print $1}' | sed "s/<//"`
	if [ $det == "csf" ]; then
		sed "${coefline}!d" *.s00$i.opt.xml | awk '{print $4}'
	fi
	if [ $det == "ci" ]; then
                sed "${coefline}!d" *.s00$i.opt.xml | awk '{print $3}'
        fi
done
